### ISSUE TITLE
Events view shows error with no filter

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#167]
## What's the Problem?

[Basecamp item](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/7082612428)

Going to the events view shows an error when there are no filter tags

## Steps to reproduce

Go here: https://liquid-church.webflow.io/events

## Screenshots/Recordings

![Screenshot 2024-02-14 at 8 41 25 AM](https://github.com/ApollosProject/apollos-embeds/assets/2659478/d9806a2c-57fa-4a69-9787-e24b337e241c)

**Comment by redreceipt** [comment]
@Sherange @rajitharussel whichever one of you gets to this first, just remove the other assignee

**Comment by redreceipt** [comment]
@vinnyjth is gonna handle this one

**Comment by redreceipt** [comment]
@vinnyjth you still gonna handle this?

**Comment by vinnyjth** [comment]
@redreceipt I think this was fixed on the server
