### ISSUE TITLE
Spacing under event title

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#180]
## What's the Problem?

[Basecamp item](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/7124316862#__recording_7127979133)

The spacing between an event title and metadata should match the spacing between the title and the image

## Steps to reproduce

Go here: https://liquid-church.webflow.io/events?id=Event-198575c8-370b-41c6-b42a-326c1d5be59a

## Screenshots/Recordings

![IMG_81F408354672-1](https://github.com/ApollosProject/apollos-embeds/assets/2659478/7179a389-0fb3-4f8b-bcff-197125d0cc9e)

**Comment by Sherange** [comment]
@redreceipt requirement here is to add more space between title and meta data right ?
![Screenshot 2024-03-05 at 8 41 32 PM 1](https://github.com/ApollosProject/apollos-embeds/assets/28708210/d270a0b4-bb17-439e-ba64-35ebb4f408da)

**Comment by redreceipt** [comment]
> @redreceipt requirement here is to add more space between title and meta data right ? ![Screenshot 2024-03-05 at 8 41 32 PM 1](https://private-user-images.githubusercontent.com/28708210/310171866-d270a0b4-bb17-439e-ba64-35ebb4f408da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTE5MjcsIm5iZiI6MTcwOTY1MTYyNywicGF0aCI6Ii8yODcwODIxMC8zMTAxNzE4NjYtZDI3MGEwYjQtYmIxNy00MzllLWJhNjQtMzVlYmI0ZjQwOGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDE1MTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNjM0Mjg3NTE1Y2FiOTQzNDFiN2QzOTE0ZGFkZTM0YmMwMTEwNDQwNDE0YzM3NzI2OWMzMTUwNGM5NTc3NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s1MAwF4FhS--GDEEgk4YxxMX5g-Yl-1Cf5stsqIm2Eg)

Correct. Match the space between the title and the image if possible.
