### ISSUE TITLE
When clicking events from a link the breadcrumbs are broken

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#181]
## What's the Problem?

[Basecamp item](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/7124316862#__recording_7128287176)

See title

## Steps to reproduce

- go here: https://liquid-church.webflow.io/events
- Click any of the event cards
- You will see "Events >" at the top

## Resolution

It should say "Events > <unlinked title>" similar to when clicking an event from the home page

## Screenshots/Recordings

https://www.loom.com/share/2bd587ca9f7d4a108c7c3b249ab2fcc2

<img width="1132" alt="Screenshot 2024-02-27 at 1 24 48 PM" src="https://github.com/ApollosProject/apollos-embeds/assets/2659478/361d51fa-f774-43c0-beb4-9e87db2a65d0">

**Comment by Sherange** [comment]
@redreceipt how we need to reset the breadcrumbs that keep adding in 
<img width="840" alt="Screenshot 2024-03-05 at 8 20 42 PM" src="https://github.com/ApollosProject/apollos-embeds/assets/28708210/30b955d2-4fbc-4fe9-bea3-3bae444dc9d5">

**Comment by redreceipt** [comment]
good question, I'm finding out...
