### ISSUE TITLE
remove predictive search section

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#184]
## Problem Statement

[Basecamp item](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/7129061118#__recording_7131972442)

We don't need the top section in search results that gives predictions if we already have results. there are a bunch of duplicates

## Resolution Criteria

- [ ] tap on search should show predictions
- [ ] typing something with no results shows predictions
- [ ] typing something with results *doesn't* show predictions too

## How to reproduce

- https://liquid-church.webflow.io
- start typing something in search

## Screenshots/Recordings

![Screenshot 2024-02-27 at 16 22 05@2x](https://github.com/ApollosProject/apollos-admin/assets/2659478/6d7fbea3-aa3b-4769-bb03-ca6620071226)

**Comment by vinnyjth** [comment]
@redreceipt I don't think this context was captured in the originating basecamp, but we _do_ want to show the predictive results under the following two scenarios: 

- you haven't searched yet (when taping on the search box, but haven't entered any text) 
- there are no results

**Comment by redreceipt** [comment]
Ok so "if there are results, don't show predictive results"

**Comment by vinnyjth** [comment]
> Ok so "if there are results, don't show predictive results"

bingo
