### ISSUE TITLE
Add CSS attribute for search bar copy

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#192]
## What's the Problem?

[Basecamp item](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/7137020839)

A user should be able to control the copy of the search bar placeholder with CSS.

## Screenshots/Recordings

<img width="612" alt="Screen Shot 2024-02-29 at 7 28 09 AM" src="https://github.com/ApollosProject/apollos-embeds/assets/2659478/a11a3814-938d-46e5-80e7-ab73c35a6656">

**Comment by Sherange** [comment]
@redreceipt as mentioned in basecamp comments this is already implemented 

![Screenshot 2024-03-25 at 3 49 56 PM](https://github.com/ApollosProject/apollos-embeds/assets/28708210/b14615b2-57e5-402f-bd3e-77b785291624)
