### ISSUE TITLE
Sharing content from micro-service should show preview in messaging apps

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#195]
## What's the Problem?

[Basecamp item](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/7150877555)

Messaging apps should show link previews of content with titles and cover images

Similar to #193 

## Steps to reproduce

https://cedar-creek.apollos.church/?id=UniversalContentItem-49e5a6c2-a006-411a-874b-e39785961896

- Share that link in a messaging app like iMessage or Android Messages

## Screenshots/Recordings
![Android](https://github.com/ApollosProject/apollos-embeds/assets/2659478/a2b438c9-f18d-4bef-8f0f-ba18a3cbaaa4)

**Comment by Sherange** [comment]
@redreceipt can I get steps and configurations to run apollos-embeds/micro-service app

**Comment by redreceipt** [comment]
@vinnyjth could you provide steps here? or potentially add it to the README? I've never booted the micro-service

**Comment by vinnyjth** [comment]
@redreceipt @Sherange I believe it's `yarn` followed by `yarn dev`. We're definitely due for a readme update.

**Comment by Sherange** [comment]
> @redreceipt @Sherange I believe it's `yarn` followed by `yarn dev`. We're definitely due for a readme update.

@vinnyjth is there any specific configuration or env variables to set, when I run yarn dev from main branch it gives empty  page 

<img width="1249" alt="Screenshot 2024-03-12 at 1 51 17 AM" src="https://github.com/ApollosProject/apollos-embeds/assets/28708210/6ed63c2e-6261-4bc4-92da-d53c99649ecb">

**Comment by vinnyjth** [comment]
@Sherange I think that's correct; the default screen may be blank.

**Comment by vinnyjth** [comment]
@Sherange It looks like you can hardcode the subdomain here

https://github.com/ApollosProject/apollos-embeds/blob/5a9963f72cbe3d9d5ab981708fefe5e42b15a26f/micro-service/src/App.js#L37-L39

From there, are you able to see the page you're looking for?

**Comment by Sherange** [comment]
@vinnyjth @redreceipt I was able to run the app by hardcoding the subdomain and when I inspect the app head element I can see the open graph tags correctly but when I run the page link through tag checker it say "**page missing open graph tags**"
<img width="1099" alt="Screenshot 2024-03-12 at 11 25 17 PM" src="https://github.com/ApollosProject/apollos-embeds/assets/28708210/6b1396f7-57b0-4dbe-af9f-b152d56262fc">
<img width="1088" alt="Screenshot 2024-03-12 at 11 28 15 PM" src="https://github.com/ApollosProject/apollos-embeds/assets/28708210/cd985f4d-0f1e-4537-b07d-6d4f37c24ef8">

**Comment by redreceipt** [comment]
@Sherange I'm not familiar with how that checker works but are you sure it's valid for `localhost` links? I would assume it runs the URL through its server.

**Comment by Sherange** [comment]
@redreceipt yes above checker runs hosted URL through its server. but I checked `localhost` with a browser extension app as well and it gives the same result. im assuming issue is with dynamic rendering I will check for a fix 

<img width="1192" alt="Screenshot 2024-03-13 at 6 29 37 PM" src="https://github.com/ApollosProject/apollos-embeds/assets/28708210/5e80b202-a0a1-4324-b7fe-682f2537450d">

**Comment by Sherange** [comment]
@redreceipt do we have developer server environment to run a test build

**Comment by redreceipt** [comment]
Good question for @vinnyjth

**Comment by vinnyjth** [comment]
Commits to a PR are automatically built using vercel

![CleanShot 2024-03-20 at 09 09 38@2x](https://github.com/ApollosProject/apollos-embeds/assets/1637694/5e678050-83c7-48b6-9a97-ffca69c57727)

**Comment by Sherange** [comment]
@redreceipt still couldn't find a solution for this issue, react helmet tags working fine but those dynamically loading tags in head section didn't detect on link share 

I try to set tags from a parent component but it didn't work (currently set in ContentSingle.js)
and I also tried with different package [react-helmet-async](https://www.npmjs.com/package/react-helmet-async)

**Comment by redreceipt** [comment]
@vinnyjth do you have any guidance or next steps here? is there a way we could build out static files at build time instead of run time somehow?

**Comment by redreceipt** [comment]
I'm gonna assign @vinnyjth to this one
