### ISSUE TITLE
add app store links to sharing page

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#214]
## What's the Problem?

[Basecamp item](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6916952946)

We should show links to the app on Apple and Google similar to the current pages served from cluster. You can use this [code](https://github.com/ApollosProject/apollos-cluster/blob/master/src/data/sharable/index.js) for reference.

## Screenshots/Recordings
![IMG_76E1E9B4B7F9-1](https://github.com/ApollosProject/apollos-embeds/assets/2659478/400efcd3-4077-4436-9175-3843e5ad7ba6)

**Comment by Sherange** [comment]
@redreceipt on what data type of web embeds should show the app store links ? do we have a design for this ?

**Comment by redreceipt** [comment]
@Sherange when you go to this [webpage](https://newspring.apollos.church/?id=WeekendContentItem-08659b7b-ebcc-4253-ae14-528ee5c3dec8) it should show the app store links at the bottom. any page shared from the micro-service should put the app store links at the bottom. you can use the design and code mentioned in the description above.
