### ISSUE TITLE
sharing content changes the formatting

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#216]
## What's the Problem?

[Basecamp item](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/7356519553#__recording_7358854800)

When sharing content on the micro-service, the content formatting is wrong. This can be seen with Cedar Creek's "Losing My Religion | Week 2" post.

## Steps to reproduce

https://cedar-creek.apollos.church/?id=UniversalContentItem-5afec465-abe1-42cd-90d5-4fe2ab928329

## Screenshots/Recordings

![Capture AI](https://github.com/ApollosProject/apollos-embeds/assets/2659478/877954bc-c5f2-4e91-90f5-4461749df3c5)
![Screenshot_2024-05-02-13-39-20-271_com android chrome](https://github.com/ApollosProject/apollos-embeds/assets/2659478/dcf0f3bb-826d-4f1e-88a1-fa0ae11cce9e)

**Comment by rajitharussel** [comment]
@redreceipt this is looks like a issue with the line height. so i increased line height a bit here, is this okay? or is there any UI i can follow?


<img width="312" alt="Screenshot 2024-05-03 at 16 40 45" src="https://github.com/ApollosProject/apollos-embeds/assets/138706838/819bf4fd-18b1-4f56-9da7-3d53bd9d0c90">

**Comment by redreceipt** [comment]
Yea that looks good

**Comment by redreceipt** [comment]
@rajitharussel do you have any updates on this item?

**Comment by rajitharussel** [comment]
> @rajitharussel do you have any updates on this item?

i was trying to recreate the conent issue. but i couldnt. i wll give a another try today and see if we can recreate it.
