### ISSUE TITLE
search is busted

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#219]
## What's the Problem?

[Basecamp item](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/7401354324)

After searching, the modal stays on screen so you can't browse

## Steps to reproduce

search for something on the Liquid site mobile

## Screenshots/Recordings

https://github.com/ApollosProject/apollos-embeds/assets/2659478/ddc9cd6b-25cd-40ae-90f6-ea65b2fe70c0

**Comment by Sherange** [comment]
@redreceipt After searching, the modal closes after user select one item or back button in search input
the correct issue is background page scroll under search modal right ?

**Comment by redreceipt** [comment]
yes that's correct
