### ISSUE TITLE
tagged events not showing up on web feeds

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#220]
## What's the Problem?

[Basecamp item](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/7283276739#__recording_7396046715)

"Prep Meal" event should be showing up on the Mercer County events feed

## Steps to reproduce

- go to the [Mercer County events feed](https://www.liquidchurch.com/af/FeatureFeed-69cc8825bbc7612068c77496e3e2d9f48ad2b8906c455d95fdbba65e3b0fe30043d83c63592e2b9827777c0c311f2481db9397d1ae6fb376c2f14202e6d92b630b1aefda88740028cfaf9718c06bd477419b58c73d6f979ae403ee7ea6aaa1f7ede715c0b0f2f1a9178352ecc65278d5a3955b361ab50e9450305229ecef654f51b29ce2b2aaaa9823e9152541a07ce221c52a59768379b22100b8928f12d8fa13005e4c95d0b622749dd131217db27cddaf10a5bb13d00645fa60cdb3849f9f5af6b2467db0dba0ee44f29ca5a609cf)
- "Prep Meal" event should be showing up

## Screenshots/Recordings

<img width="541" alt="Screenshot 2024-05-20 at 3 07 14 PM" src="https://github.com/ApollosProject/apollos-embeds/assets/2659478/feeb7fd8-9826-49bf-b642-fe1bd4a5afdf">

<img width="1582" alt="Screenshot 2024-05-20 at 3 10 08 PM" src="https://github.com/ApollosProject/apollos-embeds/assets/2659478/c2e37fc2-02e7-41a5-9336-8db0c2e1a8bc">

**Comment by Sherange** [comment]
@redreceipt when I check the graphql query result Im getting only above five events 

https://github.com/ApollosProject/apollos-embeds/assets/28708210/06d2948b-3f4f-4e6b-81a8-d0cb6c785885

**Comment by redreceipt** [comment]
@Sherange looks like that query is missing `... on Event`

**Comment by Sherange** [comment]
> @Sherange looks like that query is missing `... on Event`

@redreceipt do you mean adding `... on Event` to CardListItem -> relatedNode  ? but it didn't change the result right ?

**Comment by redreceipt** [comment]
@Sherange can you paste the query here that is being used so we can debug on the backend

**Comment by Sherange** [comment]
> @Sherange can you paste the query here that is being used so we can debug on the backend

```
query featureFeed($itemId: ID!) {
  node(id: $itemId) {
    ... on FeatureFeed {
      features {
        id
        order
        __typename      
        ... on VerticalCardListFeature {
          title
          subtitle
          cards {
            ...ContentCard
          }
        }
      }
    }
  }
}

fragment ContentCard on CardListItem {
  id
  title
  labelText
  summary
  coverImage {
    name
    sources {
      uri
    }
  }
  hasAction
  action
  actionIcon
  relatedNode {
    id
    __typename
    ... on ContentItem {
      parentItem {
        title
      }
      title
    }
    ... on Url {
      url
    }
  }
}
```

**Comment by redreceipt** [comment]
We’ll need the feature feed ID too for the query variables Sent from my iPhoneOn May 21, 2024, at 3:18 PM, Sherange Fonseka ***@***.***> wrote:﻿

@Sherange can you paste the query here that is being used so we can debug on the backend

query featureFeed($itemId: ID!) {
  node(id: $itemId) {
    ... on FeatureFeed {
      features {
        id
        order
        __typename      
        ... on VerticalCardListFeature {
          title
          subtitle
          cards {
            ...ContentCard
          }
        }
      }
    }
  }
}

fragment ContentCard on CardListItem {
  id
  title
  labelText
  summary
  coverImage {
    name
    sources {
      uri
    }
  }
  hasAction
  action
  actionIcon
  relatedNode {
    id
    __typename
    ... on ContentItem {
      parentItem {
        title
      }
      title
    }
    ... on Url {
      url
    }
  }
}

**Comment by Sherange** [comment]
@redreceipt feed id fyr
`{"itemId" : "FeatureFeed:69cc8825bbc7612068c77496e3e2d9f48ad2b8906c455d95fdbba65e3b0fe30043d83c63592e2b9827777c0c311f2481db9397d1ae6fb376c2f14202e6d92b630b1aefda88740028cfaf9718c06bd477419b58c73d6f979ae403ee7ea6aaa1f7ede715c0b0f2f1a9178352ecc65278d5a3955b361ab50e9450305229ecef654f51b29ce2b2aaaa9823e9152541a07ce221c52a59768379b22100b8928f12d8fa13005e4c95d0b622749dd131217db27cddaf10a5bb13d00645fa60cdb3849f9f5af6b2467db0dba0ee44f29ca5a609cf"}`

**Comment by redreceipt** [comment]
@Sherange can you share how that feature feed ID was generated?

**Comment by Sherange** [comment]
> @Sherange can you share how that feature feed ID was generated?

@redreceipt I took it from above link https://www.liquidchurch.com/af/FeatureFeed-69cc8825bbc7612068c77496e3e2d9f48ad2b8906c455d95fdbba65e3b0fe30043d83c63592e2b9827777c0c311f2481db9397d1ae6fb376c2f14202e6d92b630b1aefda88740028cfaf9718c06bd477419b58c73d6f979ae403ee7ea6aaa1f7ede715c0b0f2f1a9178352ecc65278d5a3955b361ab50e9450305229ecef654f51b29ce2b2aaaa9823e9152541a07ce221c52a59768379b22100b8928f12d8fa13005e4c95d0b622749dd131217db27cddaf10a5bb13d00645fa60cdb3849f9f5af6b2467db0dba0ee44f29ca5a609cf

**Comment by redreceipt** [comment]
@vinnyjth do you know how I can see what's in that encoded feature ID? trying to debug why all their Mercer events aren't showing up.

**Comment by redreceipt** [comment]
@Sherange I think this is still a website problem. Something about how that ID is being generated is wrong. The events show up in the app. You'll need to figure out where that ID comes from to continue to debug it. You get there by clicking this button:

<img width="1295" alt="Screenshot 2024-05-23 at 12 55 15 PM" src="https://github.com/ApollosProject/apollos-embeds/assets/2659478/1bef8cba-7413-48a8-811b-af8ea9fe8fb9">

**Comment by Sherange** [comment]
@redreceipt difference we having in mobile and web-embeds is the user token

I test with mobile app query and feature feed id and I get all the events but when I remove the user token from the request I get the same 5 result as in web 

then I cross checked with the web query by adding user token to it and I get all the events 

https://github.com/ApollosProject/apollos-embeds/assets/28708210/56c259c8-a486-4fc2-93bd-ebc38890ea86

**Comment by redreceipt** [comment]
So can you please lay out the queries required to reproduce the problem starting all the way from login? To debug this on the backend, we need to identify where it goes wrong on the front end. So we need all the queries in the chain.

**Comment by Sherange** [comment]
@redreceipt  Issue re-create steps with graphql queries

1 - get user token from login [query](https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fcdn.apollos.app&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4RxighigSwiQAIA3XAGwLHwQBkIBzApACgBIblCUBPdCQCCOABY8CUfESQBJMBP6ykABxwBCADQkOEFCsEBlFACdWTdQEoSwADqlyVGnUYt23VAX6CuCz-209Ax0g6zsHEhIVBBMAZ2Ibe0jkkhoklJIAMwI4lAA5XER0lMpcWPzChGLkpEkAawKiiOSEOFwCSmrIpmQFEy6SACMclFEAEToBlVFiKuaAX2rcKCgEWNiAFQg65GqTBEz92NEtnaRq8v3C092HRaR5kE0QCjNcQco1jBBwyNsQDy8Pj-QS-ZL-VrtToYEj-XAqFTlCD7FBrVEmAAC8IglEoEFiADp4Sp-ul5pp0v8giDYSAAIwAJgAzAAWUkPJ4gcS4Pqxb52EAADwAtFBRDATGKQf9qABHGA0AD6YolUpAj3mQA)
2 - feature feed query to get [event list](https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fcdn.apollos.app&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAGYICGKMeCAYggmABQAkAlignAJJjpHcAIgEIAlEWAAdJEVlEkEMAiZs%2BRdpx5hxUmXNkA6I0Qgz6lanQZgJ0-frIWaAZ1t77c1XY9yIeJXjePkQA%2BiEoBAAOyOSI0kE%2BRgYmMgDCABZskQAybM4o5lQ0bsH6KBwANggJwc4wAEblKFU1PlCZka66pfZNLe49RORQ5aatwWxQpgBysdUDPV4LpTQVlIzTigglg-pJKUQAqngVO7v6YRHRSHPjg9QVd8EAvk-2r8seHz0fb-umRAAgiM2KYAELkPCFSxnUp9ea7YajJBdN76JbnIiTMafHzwtFyJGgpAE2SrdZgTZKWG7f4yY6nbqYuSXKIxOK4noPUlyb7nPk-N6-TlEOlAkGmXL5aHFJk9fEi2R1RqVBGDImmVGKzxgHkKzHK-XnDUk7WyNhwcgAc22cvOzgg1CgCC1zLk1DYPP09Qq1AAEuRnOkvUQBYMwz1yZxKVsaYNWddbmadTyIz40-phT0xQBRABuyBQYIq0AA1jLbQSMYN8pCUASwNRKMSq1BnAyCeQKhVBOQCASS1BmzjdkaXvERWK-X42AAvUwoLsAWUYbHIUoKFCKle11flqqrmld5z38fCbJuHMxY8GUwLeG4lptcZ6DqdLpf9zwnuTsgz6Z5KMNljO1dlPXYE3ZNVMTFVIF0LbhNE-fdmmg5k81UBAIGPN1DCMAA1TCIBXMA11oNgEAqMBnBDP8Q3-YIxQZZDSm5X9QxDMVcgLfIaFiFjghvA1Fzwet2NkRs8GHJBuCQABlBApiQajaKIXiKDgATSnA5kZytNgZN1cTfG-fSkAAFTZVSJKbZFrLUx08GdHDcNkD17IY0pPK%2BVMCU8zypxnedUC7VJITADcKy0oSfENA9tSHfwXOzIw4NQQswv8QDKIpKkdzdHSekgy80NpYwATSzhUEQrgtI8GLdgwpRsLqxICKIkiyIoqiaOM7z3k48r6ROVr9DYt1%2Bro7V%2Bsib9LUIYFkVahqfBNbK1mjPLRqxIy3WKpM3Vg%2BDqqQ0DzhWnomqw5LmSSQjms68hyMolS%2Bvo3zpqFP4hqIfD8HKIcKkyiK8k3Jx8sGC65Di1CCUS6jWqSSqMvCvyvsnH6AAUpIIfBIq3GEzo8Qreni3YYf6XY-ACKtnGBglZr7fAbuCfarxPXbzoQAAPMTMTybGmc5sDnEBBQkAIOBHV6zEaBwF0UD8baSDYPB8lmdnMTWdWDuZG1lPwEN6lVlB0l7TgQ0idIIEV7a3O-d7k36-zvuSAE-XwCB8fBrSSbKMmawaKHZHST3gcR1LjpQenkyAmNqSJ0ojvSk7asTno9IM3hVMziyrPYyaOM%2B7UAGIiHM0PnG2IcZHqavwoAWgqNhS22DguGcAAaeQbaIAArGB8iIeoYBQRWUU7CUUVav3Sdh5MKdK0o1tjnLNpAkNZ48Nml5St20ijmrNPTuEA8xQvC4ta0IYNRznLtoh3ILj7dhmubIQIRbiWWs-1Sn9bcob3YlvewO9Br7yIMjVOx9VLBwGk7NGIoAo-TBKPceUUT6yBND-eemIV6yzXsBBOm9hbnDAexJiI1ME%2BHGsyC%2BiDBQYwgX6FAcAKgYLhlHdGe8DhySgN%2BSI24OHamcPwrI24WY%2BBASHVhjxV5kBoEgZ0PIpiRAIKZdIfNzj3mcC2ZMnBeYMK8ncNMYYPjChIFJK0iBUCQKjuHCq4UNxHx2NWI0aw64VHMjzLRdQ4DzX7HoO8%2BBHzX1hCVBIb4nIfjOk-TM3g%2BTpEDF-EcQx-56BNNwJS3g45bTtKechewfpQJQC4s6kRIQIVOncGKaYbxhkoYyVotCppTSzKQKxNiUC-Q6quJ63UEYAnulhR6sJCkpgGK3QJ%2BgIkDCiffWJDsBhhkktJBIg98DYwgFaFwN1IhrAIKHcgpDZBTDgPshAFtlkJC4HXMALC2EJOkCATuIA8yQjXD6F0GAQBSBAO3LQkgQBEH4ECis9BGDoAAGwAE4oBQAABwIoAEwAFZ6j1CgAAdihQARmRQABihQi7FWKAAsMKoUIAAMwIGRWAGFJAyUIuOci%2BoCKYVEqgGS1FqKGWopIGADF5AoWoppfUAlZBqUEoJWS6lYAEXUqgFC6lqKYXIrpfUGFKKsW6qxVAAlUBqW4txSQZFzLcVCphdSmFWKwC4vIAgKFJB6jUpxVAZFJBcVksJRqqFDK2UqoJfUB1CBBXkCReSmVyKSUkHICQW1uKSVEvqGAMluqyW4phfUVFJKsXyudbamFjqyUEtpQgLFFAoXkBraaytSgsW4tRQaiVZqvXkBhbirFirUUavhaK5F3awCovIDa3lrq8XkBzQShAMKeVloJb25FMLFJhtFWSkgqLcX1GXc6NlyKa01u1ci2lnbe2oszeQAl%2Bq6XItxVAXt5A1U4sVVi7NyK70yvZeqhFXr6W-vILi6Vi6EBkqgDCvlwaoUfvJTCsA9rjV3rtTu-V8H424oJU%2BjFQGwAyqhTyuNULDVCupQiilCbN3xqhTuslULkMEqFVehgZKN27qfSKglcKSBAueC8kARyAjOB%2BX87mDd2hOmDBgIFzccCqBCOJpyknePPCAA) 
3 - Add authorization token to step 2 query to get [all events ](https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fcdn.apollos.app&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAGYICGKMeCAYggmABQAkAlignAJJjpHcAIgEIAlEWAAdJEVlEkEMAiZs%2BRdpx5hxUmXNkA6I0Qgz6lanQZgJ0-frIWaAZ1t77c1XY9yIeJXjePkQA%2BiEoBAAOyOSI0kE%2BRgYmMgDCABZskQAybM4o5lQ0bsH6KBwANggJwc4wAEblKFU1PlCZka66pfZNLe49RORQ5aatwWxQpgBysdUDPV4LpTQVlIzTigglg-pJKUQAqngVO7v6YRHRSHPjg9QVd8EAvk-2r8seHz0fb-umRAAgiM2KYAELkPCFSxnUp9ea7YajJBdN76JbnIiTMafHzwtFyJGgpAE2SrdZgTZKWG7f4yY6nbqYuSXKIxOK4noPUlyb7nPk-N6-TlEOlAkGmXL5aHFJk9fEi2R1RqVBGDImmVGKzxgHkKzHK-XnDUk7WyNhwcgAc22cvOzgg1CgCC1zLk1DYPP09Qq1AAEuRnOkvUQBYMwz1yZxKVsaYNWddbmadTyIz40-phT0xQBRABuyBQYIq0AA1jLbQSMYN8pCUASwNRKMSq1BnAyCeQKhVBOQCASS1BmzjdkaXvERWK-X42AAvUwoLsAWUYbHIUoKFCKle11flqqrmld5z38fCbJuHMxY8GUwLeG4lptcZ6DqdLpf9zwnuTsgz6Z5KMNljO1dlPXYE3ZNVMTFVIF0LbhNE-fdmmg5k81UBAIGPN1DCMAA1TCIBXMA11oNgEAqMBnBDP8Q3-YIxQZZDSm5X9QxDMVcgLfIaFiFjghvA1Fzwet2NkRs8GHJBuCQABlBApiQajaKIXiKDgATSnA5kZytNgZN1cTfG-fSkAAFTZVSJKbZFrLUx08GdHDcNkD17IY0pPK%2BVMCU8zypxnedUC7VJITADcKy0oSfENA9tSHfwXOzIw4NQQswv8QDKIpKkdzdHSekgy80NpYwATSzhUEQrgtI8GLdgwpRsLqxICKIkiyIoqiaOM7z3k48r6ROVr9DYt1%2Bro7V%2Bsib9LUIYFkVahqfBNbK1mjPLRqxIy3WKpM3Vg%2BDqqQ0DzhWnomqw5LmSSQjms68hyMolS%2Bvo3zpqFP4hqIfD8HKIcKkyiK8k3Jx8sGC65Di1CCUS6jWqSSqMvCvyvsnH6AAUpIIfBIq3GEzo8Qreni3YYf6XY-ACKtnGBglZr7fAbuCfarxPXbzoQAAPMTMTybGmc5sDnEBBQkAIOBHV6zEaBwF0UD8baSDYPB8lmdnMTWdWDuZG1lPwEN6lVlB0l7TgQ0idIIEV7a3O-d7k36-zvuSAE-XwCB8fBrSSbKMmawaKHZHST3gcR1LjpQenkyAmNqSJ0ojvSk7asTno9IM3hVMziyrPYyaOM%2B7UAGIiHM0PnG2IcZHqavwoAWgqNhS22DguGcAAaeQbaIAArGB8iIeoYBQRWUU7CUUVav3Sdh5MKdK0o1tjnLNpAkNZ48Nml5St20ijmrNPTuEA8xQvC4ta0IYNRznLtoh3ILj7dhmubIQIRbiWWs-1Sn9bcob3YlvewO9Br7yIMjVOx9VLBwGk7NGIoAo-TBKPceUUT6yBND-eemIV6yzXsBBOm9hbnDAexJiI1ME%2BHGsyC%2BiDBQYwgX6FAcAKgYLhlHdGe8DhySgN%2BSI24OHamcPwrI24WY%2BBASHVhjxV5kBoEgZ0PIpiRAIKZdIfNzj3mcC2ZMnBeYMK8ncNMYYPjChIFJK0iBUCQKjuHCq4UNxHx2NWI0aw64VHMjzLRdQ4DzX7HoO8%2BBHzX1hCVBIb4nIfjOk-TM3g%2BTpEDF-EcQx-56BNNwJS3g45bTtKechewfpQJQC4s6kRIQIVOncGKaYbxhkoYyVotCppTSzKQKxNiUC-Q6quJ63UEYAnulhR6sJCkpgGK3QJ%2BgIkDCiffWJDsBhhkktJBIg98DYwgFaFwN1IhrAIKHcgpDZBTDgPshAFtlkJC4HXMALC2EJOkCATuIA8yQjXD6F0GAQBSBAO3LQkgQBEH4ECis9BGDoAAGwAE4oBQAABwIoAEwAFZ6j1CgAAdihQARmRQABihQi7FWKAAsMKoUIAAMwIGRWAGFJAyUIuOci%2BoCKYVEqgGS1FqKGWopIGADF5AoWoppfUAlZBqUEoJWS6lYAEXUqgFC6lqKYXIrpfUGFKKsW6qxVAAlUBqW4txSQZFzLcVCphdSmFWKwC4vIAgKFJB6jUpxVAZFJBcVksJRqqFDK2UqoJfUB1CBBXkCReSmVyKSUkHICQW1uKSVEvqGAMluqyW4phfUVFJKsXyudbamFjqyUEtpQgLFFAoXkBraaytSgsW4tRQaiVZqvXkBhbirFirUUavhaK5F3awCovIDa3lrq8XkBzQShAMKeVloJb25FMLFJhtFWSkgqLcX1GXc6NlyKa01u1ci2lnbe2oszeQAl%2Bq6XItxVAXt5A1U4sVVi7NyK70yvZeqhFXr6W-vILi6Vi6EBkqgDCvlwaoUfvJTCsA9rjV3rtTu-V8H424oJU%2BjFQGwAyqhTyuNULDVCupQiilCbN3xqhTuslULkMEqFVehgZKN27qfSKglcKSBAueC8kARyAjOB%2BX87mDd2hOmDBgIFzccCqBCOJpyknO5AsBKPa235ZxrKkyAMEFAaB4CIAgAgAApdI9QADiUA2AAHk2DGe4IcWc3BcXTDYNwZwskABKzbUjcChdwUskQAAa%2BFUjGZhQYIzxmADuAAtILxnZw7tRcZ2Lvn-N90OGS6YcAcwEuswAdWM33bIBW8uxcEAATRQNMQQjmlxsEXdMPuUBoulemOkSrBXKvIumLOWLFRYvmRzNS6Ycl3OPipAlvu5B0uPm5pEKAIXIixdoDCmbfp8IEB6-pbIYXIiVaCwARRs33EbS5zKVdRUuQQgJosXbbI%2BfCYH0sPe5s10s2W%2B5Hfe9Kgw6R82lhgH3LC2R-FySO%2BZbIIRSz1DBAVhFCA5JYBQLizGlLzKxfIBAWgR3siRCXJEJAsXSwEp4yAZ4QA)

**Comment by redreceipt** [comment]
@Sherange where is the `itemId` coming from for the feature feed? I have no way of knowing if that feature feed ID is valid. do you know how that ID is being generated after clicking the "View All" button in my screenshot above?

**Comment by Sherange** [comment]
> @Sherange where is the `itemId` coming from for the feature feed? I have no way of knowing if that feature feed ID is valid. do you know how that ID is being generated after clicking the "View All" button in my screenshot above?

@redreceipt I manage to debug how "View All" generated, use the same feature feed query with feed id `{"itemId" : "FeatureFeed:c97d388b-9115-4ce9-b37e-7b9da66fac73"}` then you get the primary action data for view more button
![Screenshot 2024-05-29 at 4 35 50 PM](https://github.com/ApollosProject/apollos-embeds/assets/28708210/2d43a613-2c0d-448a-bd98-1d58782399f9)
![Screenshot 2024-05-29 at 4 33 18 PM](https://github.com/ApollosProject/apollos-embeds/assets/28708210/11a252d6-f7f0-4ce3-98a5-f3f4f56c00fc)

**Comment by redreceipt** [comment]
excellent work @Sherange. i just figured out that the response is different if a user is logged in

|auth|no auth|
|---|---|
|<img width="1792" alt="Screenshot 2024-05-29 at 6 04 53 PM" src="https://github.com/ApollosProject/apollos-embeds/assets/2659478/ccf167e8-3c4b-43a2-95f0-b5a5966b7891">|<img width="1792" alt="Screenshot 2024-05-29 at 6 05 23 PM" src="https://github.com/ApollosProject/apollos-embeds/assets/2659478/b2ad4dff-766b-46c0-be02-bc3054f0f776">|

debugging on the backend now

**Comment by redreceipt** [comment]
this is a backend problem, the response is different when there's no auth header (like what's on the website)
