### ISSUE TITLE
Berean web embed is busted

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#224]
## Problem Statement

[Linear issue](https://linear.app/differential/issue/APO-142/berean-embeds-all-broken)
PR Branch Name: `apo-142-berean-embeds-all-broken`

This link doesn't show anything in the embed: https://bereanchristianchurch.webflow.io/watch

## Resolution Criteria

There are items in the feed

## How to reproduce

Go to the link: https://bereanchristianchurch.webflow.io/watch

## Screenshots/Recordings

<img width="1872" alt="Screenshot 2024-06-25 at 12 01 32 PM" src="https://github.com/ApollosProject/apollos-embeds/assets/2659478/fe316909-2185-4bc2-8351-f8f60855388a">

**Comment by rajitharussel** [comment]
Hi @redreceipt ,

I was trying to recreate this issue using an embedded application but it works fine with the local embeds app. I was able to extract the feed ID by inspecting the website given above. and I found the relevant feed from the admin panel. so I applied the embedding code and it's working as expected.  


<img width="1434" alt="Screenshot 2024-06-27 at 14 31 00" src="https://github.com/ApollosProject/apollos-embeds/assets/138706838/3fbe263a-ed11-4ee7-aba9-af3ebf9177dd">
<img width="1439" alt="Screenshot 2024-06-27 at 14 31 25" src="https://github.com/ApollosProject/apollos-embeds/assets/138706838/7113fc57-a380-402c-aae8-14ccdb2445ad">
<img width="721" alt="Screenshot 2024-06-27 at 14 31 50" src="https://github.com/ApollosProject/apollos-embeds/assets/138706838/fbae4559-dd5c-496e-b6c0-9dcf692298af">


then I was trying to figure out what was the issue with the website given. and I found that the web page does not contain the CSS and JS files not included. as mentioned here
<img width="1357" alt="Screenshot 2024-06-27 at 14 48 18" src="https://github.com/ApollosProject/apollos-embeds/assets/138706838/9fa15fc1-887b-48da-b7c1-eb4965e30f77">

<img width="1433" alt="Screenshot 2024-06-27 at 14 40 30" src="https://github.com/ApollosProject/apollos-embeds/assets/138706838/7aab1c45-1e50-4a4f-a224-20958ca266d3">

**Comment by redreceipt** [comment]
@rajitharussel it's there now

<img width="1872" alt="Screenshot 2024-06-27 at 10 48 52 AM" src="https://github.com/ApollosProject/apollos-embeds/assets/2659478/12844728-c2f8-4ba6-bd93-1123b2c25584">

**Comment by rajitharussel** [comment]
Hi @redreceipt ,

still, there is a network failure.
<br/>
<img width="718" alt="Screenshot 2024-06-28 at 11 39 56" src="https://github.com/ApollosProject/apollos-embeds/assets/138706838/c47a11b7-6d4d-40a3-ba14-12cb472acb3b">

looks like the church is wrong
<br/>
<img width="719" alt="Screenshot 2024-06-28 at 11 40 07" src="https://github.com/ApollosProject/apollos-embeds/assets/138706838/5c9b1d36-a8a0-423b-a9c4-78380af1286c">
<br/>
so I tried same request with postman. and got same error
<br/>
![Screenshot 2024-06-28 at 11 41 32](https://github.com/ApollosProject/apollos-embeds/assets/138706838/36d60245-4ce8-4802-a073-6cd038cc48f3)
<br/>
if we change the church it works fine.
<br/>
![Screenshot 2024-06-28 at 11 41 46](https://github.com/ApollosProject/apollos-embeds/assets/138706838/604d31a2-fcd0-4ac7-b00b-e0c96f8c025b)
<br/>
so I guess changing this one should work right?
<br/>
<img width="1435" alt="Screenshot 2024-06-28 at 11 39 39" src="https://github.com/ApollosProject/apollos-embeds/assets/138706838/27a6aef8-8b89-429c-ae4e-2be4db80fa7b">

**Comment by redreceipt** [comment]
I think you're probably right. Good find. I'll let the Webflow team know.
