### ISSUE TITLE
search bar words overflowing

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#232]
## Problem Statement

[Linear issue](https://linear.app/differential/issue/APO-1022/seacoast-search-bar-alignment)
PR Branch Name: `apo-1022-seacoast-search-bar-alignment`

Words are running outside the search bar.

https://seacoast-church.webflow.io/

## Screenshots/Recordings

![Screenshot 2024-11-18 at 1 41 15 PM](https://github.com/user-attachments/assets/8ad4d156-5375-450d-b812-fbef243ff2d3)

**Comment by jimmyhogoboom** [comment]
I've had a couple people mention that Seacoast might be on an old version of web embeds. Maybe we should get them on the latest version before we spend any more time looking in to this? (I haven't been able to recreate this issue locally)

**Comment by redreceipt** [comment]
You should be able to inspect the source on their reduction site? I expect npm latest

**Comment by jimmyhogoboom** [comment]
Yeah, confirmed that they are actually on latest.
