### ISSUE TITLE
search not showing web results

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#250]
## Problem Statement

[Linear issue](https://linear.app/differential/issue/APO-1183/liquid-search-issues#)
PR Branch Name: `apo-1183-liquid-search-issues`

on `liquid_church` searching for "christmas eve services" is not returning https://www.liquidchurch.com/christmas-eve-services-2024 in the results 

## Resolution Criteria

- [ ] Searching for "christmas eve services" on `liquid_church` should return https://www.liquidchurch.com/christmas-eve-services-2024 in the results

## Screenshots/Recordings

<img width="1402" alt="Screenshot 2024-12-17 at 10 05 10 AM" src="https://github.com/user-attachments/assets/ea143158-b3fe-4f09-83aa-a24b426fdfe4" />

**Comment by jimmyhogoboom** [comment]
I logged into Algolia and tried the search, and it doesn't show up there either. I'm not familiar with Algolia, but I'll keep digging.

**Comment by jimmyhogoboom** [comment]
You are correct. I'm looking at that index on Algolia, and the page we're looking for is not appearing in those results.

**Comment by jimmyhogoboom** [comment]
collections

**Comment by jimmyhogoboom** [comment]
<img width="801" alt="Screenshot 2024-12-20 at 9 05 17 AM" src="https://github.com/user-attachments/assets/c3896790-22e2-4fa3-90c3-b738657ba699" />

**Comment by jimmyhogoboom** [comment]
So we need to look at how that index is built. Is that done in Shovel somewhere?

**Comment by redreceipt** [comment]
ok, we index via shovel in the pages DAG so you may have to debug there to figure out if the expected page is even showing up

**Comment by jimmyhogoboom** [comment]
Ok if I'm reading this right, the DAG is looking at https://www.liquidchurch.com/ and using a `usp.tree` import called `sitemap_tree_for_homepage` to build a list of pages to index.

Looking at the DAG logs (which were extremely helpful) the Christmas Eve 2024 page is not listed. 

So I think they haven't posted that Christmas Eve post anywhere on their site?

**Comment by redreceipt** [comment]
https://www.liquidchurch.com/christmas-eve-services-2024 it's live so we need to figure out how to get it in

**Comment by jimmyhogoboom** [comment]
Right, but do they have a link to that anywhere on their site? Right now it exists as an orphan page, and we can only get to it if you know the link. I think a link to that post has to exist somewhere on the site for it to show up in Algolia
